### ISSUE TITLE
USER STORY: RUNNER

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/my-first-agile-project#3]
As a **runner** I can **engage with the poll** so that **I can join running events to socialise or improve my ability**.

## **Acceptance criteria:**

- Enter data into the poll
- Receive feedback that the poll has been completed
- Sign up option to input email and provide feedback on progress of the poll

## **Tasks**

- [ ] Create form to enter data into and submit button
- [ ] Create form to request user email and add to excel sheet
- [ ] Create output message template that can be updated with aggregated, anonymised user input data to output to user

**Comment by MattuW4** [comment]
This is completed
